### ISSUE TITLE
twrp-3.7.0_12-0-payton bootloop

### ISSUE THREAD

**Issue by rommelfm** [TeamWin/android_device_motorola_payton#4]
_Hello,
I'm using TWRP-3.6.2_11  on my XT1900-7 and anything worked fine. Since updating from Lineageos 18 to 19 (Android 12) TWRP can't decrypt the data partition._
So I tried flashing twrp-installer-3.7.0_12-0-payton.zip and ended with a bootloop. The phone shows the Moto X4 logo three times ans shuts down.
I tried the twrp-3.7.0_12-0-payton.img via fastboot but it's the same. _So I went back to TWRP-3.6.2._
I unzipped the twrp-installer-3.7.0_12-0-payton.zip on my Computer to check if it is corrupted but all files are OK.

**Comment by bigbiff** [comment]
Thanks for letting me know. I have removed the files and disabled future jobs from running until a maintainer can update the tree.
